version: '3.8'

services:
  backend:
    build:
      context: ./back-end
    ports:
      - "5252:5252"
    container_name: flask-back-end

  frontend:
    build:
      context: ./front-end
    ports:
      - "9000:9000"
    container_name: softy-pinko-front-end
